version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "9000:9000"
    command: /bin/sh -c "sleep 5 && daphne hackday2023.asgi:application -u /tmp/daphne.sock -p 9000 -b 0.0.0.0"
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "hackday2023", "worker", "--loglevel=info", "--concurrency=1"]
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"

volumes:
  mysql_data:

# networks:
#   default:
#     external:
#       name: hackday2023
